### ISSUE TITLE
Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times

### ISSUE THREAD

**Issue by ibc** [latysheff/node-sctp#15]
I'm getting the following **fatal** error. I don't know yet when/why it happens (on it). However, it's a **fatal** error because it's an internal unhandled "error" event, so it terminates the Node process.

```
Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
    at onwrite (_stream_writable.js:465:11)
    at /Users/ibc/xxxxxxx/node_modules/sctp/lib/sockets.js:134:9
    at /Users/ibc/xxxxxxx/node_modules/sctp/lib/sockets.js:174:11
    at /Users/ibc/xxxxxxx/node_modules/sctp/lib/association.js:1658:11
    at /Users/ibc/xxxxxxx/node_modules/sctp/lib/association.js:1335:13
    at Array.forEach (<anonymous>)
    at /Users/ibc/xxxxxxx/node_modules/sctp/lib/association.js:1332:19
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Note that I'm setting an "error" listener in the node-sctp `Socket` instance, so the problem is that such a "error" exception is not being caught internally.

**Comment by ibc** [comment]
The data being sent via the SCTP stream is as follows:

```js
data = '{"event":"bomberman-start-game","payload":{"id":"ibc@mycompany","mapName":"cold_map","layerInfo":{"name":"Blocks","width":28,"height":18,"x":0,"y":0,"data":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,3,3,3,3,2,1,2,3,2,3,2,3,2,3,2,3,2,3,1,2,3,3,3,2,3,1,1,3,2,1,1,3,2,2,3,2,3,2,3,2,3,2,3,2,3,2,1,3,3,2,2,2,3,1,1,2,3,3,3,3,3,2,3,1,1,1,1,3,1,1,1,1,2,3,2,3,3,1,1,1,2,1,1,1,1,1,2,2,2,2,3,3,3,2,3,3,3,3,3,2,3,3,1,2,3,3,3,3,3,1,1,3,3,3,2,3,3,3,3,2,2,3,3,2,1,1,3,3,2,3,1,2,3,3,2,3,2,1,1,2,2,3,1,1,1,1,2,2,1,1,1,1,1,1,2,2,1,1,3,2,1,1,1,2,1,1,1,2,2,3,2,3,3,1,3,3,1,1,3,3,2,2,3,3,2,2,3,3,2,1,3,3,3,1,1,1,1,1,2,3,3,1,3,2,3,3,2,3,3,3,3,3,3,3,3,3,1,1,3,2,2,1,1,3,3,3,3,3,3,1,3,2,2,2,2,3,1,1,1,1,1,2,3,3,1,2,3,2,1,1,1,3,2,1,1,2,3,1,3,3,3,3,3,3,1,3,3,3,3,2,3,2,3,2,3,2,2,1,1,1,2,2,2,2,3,1,1,1,2,2,2,1,1,2,3,2,3,2,3,2,3,2,2,3,3,1,1,3,3,3,3,3,3,3,3,3,3,2,3,2,3,3,2,3,2,1,1,1,1,1,2,3,3,1,1,1,1,2,2,1,1,2,2,2,3,3,2,2,2,3,3,3,3,2,3,2,3,1,1,1,1,1,1,2,3,3,3,3,3,3,3,1,2,3,1,1,1,1,2,2,3,1,2,2,3,2,2,2,2,1,1,3,2,2,1,2,3,2,3,1,3,2,3,2,3,2,3,2,3,2,3,1,1,3,3,3,3,1,1,3,3,2,3,2,1,2,3,1,3,3,2,3,2,3,2,3,3,1,3,3,3,3,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"opacity":1,"type":"tilelayer","visible":true,"properties":{"max_players":16,"collisionTiles":[1,2],"empty":3,"balk":2,"wall":1,"spawns":[{"col":6,"row":3},{"col":8,"row":14},{"col":20,"row":15},{"col":22,"row":1},{"col":5,"row":5},{"col":3,"row":12},{"col":26,"row":7},{"col":19,"row":4},{"col":13,"row":4},{"col":16,"row":13},{"col":18,"row":10},{"col":2,"row":5},{"col":8,"row":8},{"col":20,"row":8},{"col":5,"row":9},{"col":25,"row":11}]}},"players":{"ijqwgukkizuKNHS5AAAA":{"id":"ijqwgukkizuKNHS5AAAA","spawnGroup":0,"spawn":{"x":192,"y":96},"position":{"x":192,"y":96},"spawnOnGrid":{"col":6,"row":3},"name":"Iñaki","isAlive":true,"power":1}},"playerSpawnsGroups":[[{"col":8,"row":14},{"col":20,"row":15},{"col":22,"row":1}],[{"col":5,"row":5},{"col":3,"row":12},{"col":26,"row":7},{"col":19,"row":4}],[{"col":13,"row":4},{"col":16,"row":13},{"col":18,"row":10},{"col":2,"row":5}],[{"col":8,"row":8},{"col":20,"row":8},{"col":5,"row":9},{"col":25,"row":11}]],"shadowMap":[[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,2,0,0,0,0,2,1,2,0,2,0,2,0,2,0,2,0,2,0,1,2,0,0,0,2,0,1],[1,0,2,1,1,0,2,2,0,2,0,2,0,2,0,2,0,2,0,2,1,0,0,2,2,2,0,1],[1,2,0,0,0,0,0,2,0,1,1,1,1,0,1,1,1,1,2,0,2,0,0,1,1,1,2,1],[1,1,1,1,2,2,2,2,0,0,0,2,0,0,0,0,0,2,0,0,1,2,0,0,0,0,0,1],[1,0,0,0,2,0,0,0,0,2,2,0,0,2,1,1,0,0,2,0,1,2,0,0,2,0,2,1],[1,2,2,0,1,1,1,1,2,2,1,1,1,1,1,1,2,2,1,1,0,2,1,1,1,2,1,1],[1,2,2,0,2,0,0,1,0,0,1,1,0,0,2,2,0,0,2,2,0,0,2,1,0,0,0,1],[1,1,1,1,2,0,0,1,0,2,0,0,2,0,0,0,0,0,0,0,0,0,1,1,0,2,2,1],[1,0,0,0,0,0,0,1,0,2,2,2,2,0,1,1,1,1,1,2,0,0,1,2,0,2,1,1],[1,0,2,1,1,2,0,1,0,0,0,0,0,0,1,0,0,0,0,2,0,2,0,2,0,2,2,1],[1,1,2,2,2,2,0,1,1,1,2,2,2,1,1,2,0,2,0,2,0,2,0,2,2,0,0,1],[1,0,0,0,0,0,0,0,0,0,0,2,0,2,0,0,2,0,2,1,1,1,1,1,2,0,0,1],[1,1,1,2,2,1,1,2,2,2,0,0,2,2,2,0,0,0,0,2,0,2,0,1,1,1,1,1],[1,2,0,0,0,0,0,0,0,1,2,0,1,1,1,1,2,2,0,1,2,2,0,2,2,2,2,1],[1,0,2,2,1,2,0,2,0,1,0,2,0,2,0,2,0,2,0,2,0,1,1,0,0,0,0,1],[1,0,0,2,0,2,1,2,0,1,0,0,2,0,2,0,2,0,0,1,0,0,0,0,2,2,2,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]],"spoils":{},"bombs":{}}}'
```

...which is **3214** bytes long.

And I'm using it as follows:

```js
const sctp = require('sctp');
const dgram = require('dgram');

// Set node-sctp default PMTU to 1200. <----- UPPS ?
sctp.defaults({ PMTU: 1200 });

const udpSocket = dgram.createSocket({ type: 'udp4' });

// Connect the udpSocket and so on
// [...]

const sctpSocket = sctp.connect({
      localPort: 5000, // Required for SCTP over plain UDP in mediasoup.
      port: 5000, // Required for SCTP over plain UDP in mediasoup.
      OS: 128,
      MIS: 128,
      unordered: false,
      udpTransport: udpSocket, // previously created
      udpPeer: {
        address: remoteUdpIp,
        port: remoteUdpPort,
      },
    });

// Wait for the SCTP socket to be connected (SCTP association done)
// [...]

// Send data above
const buffer = Buffer.from(JSON.stringify(data));

// Set ppid of type WebRTC DataChannel string.
buffer.ppid = sctp.PPID.WEBRTC_STRING;

sctpStream.write(buffer);
```

BTW super confirmed that the error happens due the size of `data` (**3214** bytes). It does not happen with smaller data. It also happens if I remove the `sctp.defaults({ PMTU: 1200 });` line.

**Comment by ibc** [comment]
Here a code that reproduces the issue. Just place it into a new folder and install `npm i mediasoup@3 sctp` on that folder.

Then run it by passing different `PMTU` values as command line argument and you'll see the problem.

```js
const dgram = require('dgram');
const mediasoup = require('mediasoup');
const sctp = require('sctp');

const PMTU = Number(process.argv[2]);

if (!PMTU) {
  console.error('[ERROR]: missing PMTU comamnd line argumentrun');

  process.exit(1);
}

run()
  .then(() => {
    console.log('[INFO] run() succeeds :)');

    process.exit(0);
   })
  .catch((error) => {
    console.error('[ERROR]: run() failed: %o', error);

    process.exit(1);
  });

async function run() {
  console.log('[INFO] running with PMTU %s', PMTU);

  // Set PMTU for SCTP.
  sctp.defaults({ PMTU: PMTU });

  console.log('[INFO] creating a mediasoup Worker, Router and PlainRtpTransport...');

  // Create a mediasoup Worker.
  const worker = await mediasoup.createWorker();

  // Create a mediasoup Router.
  const router = await worker.createRouter();

  // Create a mediasoup PlainRtpTransport for connecting the node-sctp.Socket.
  const transport = await router.createPlainRtpTransport({
    listenIp: { ip: '127.0.0.1' },
    enableSctp: true,
    numSctpStreams: { OS: 512, MIS: 512 },
    maxSctpMessageSize: 1000000, // 1 Mbit
    appData: { 'node-sctp': true },
  });

  console.log('[INFO] creating a UDP socket...');

  // Node UDP socket for SCTP.
  const udpSocket = dgram.createSocket({ type: 'udp4' });

  await new Promise(resolve => udpSocket.bind(0, '127.0.0.1', resolve));

  const localUdpPort = udpSocket.address().port;

  // Connect the mediasoup PlainRtpTransport to the UDP socket port.
  await transport.connect({ ip: '127.0.0.1', port: localUdpPort });

  console.log('[INFO] creating a SCTP socket...');

  // Create a node-sctp Socket.
  const sctpSocket = sctp.connect({
    localPort: 5000, // Required for SCTP over plain UDP in mediasoup.
    port: 5000,      // Required for SCTP over plain UDP in mediasoup.
    OS: transport.sctpParameters.OS,
    MIS: transport.sctpParameters.MIS,
    unordered: false,
    udpTransport: udpSocket,
    udpPeer: {
      address: transport.tuple.localIp,
      port: transport.tuple.localPort,
    },
  });

  sctpSocket.on('error', (error) => {
    Logger.error('[ERROR] node-sctp socket "error" event: %o', error);

    process.exit(2);
  });

  console.log('[INFO] waiting for the SCTP assoiation to be open...');

  // Wait for the SCTP association to be open.
  try {
    await Promise.race([
      new Promise((resolve, reject) => {
        setTimeout(() =>
        {
          reject(new Error('SCTP connection timeout'));
        }, 2000);
      }),
      new Promise(resolve => sctpSocket.on('connect', resolve)),
    ]);
  } catch (error) {
    transport.close();
    udpSocket.close();
    sctpSocket.end();

    throw error;
  }

  console.log('[INFO] creating a SCTP stream...');

  // Create a SCTP Stream with id 1 (don't use the implicit Stream in the
  // node-sctp Socket).
  const sctpStream = sctpSocket.createStream(1);

  console.log('[INFO] creating a mediasoup DataProducer associated to the SCTP stream...');

  // Create a mediasoup DataProducer representing the SCTP Stream.
  const dataProducer = await transport.produceData({
    sctpStreamParameters: {
      streamId: 1,
      ordered: true,
    }
  });

  // NOTE:
  //
  // Whether those sizes work or not depend on the PMTU. If the size is bigger
  // than the PMTU then node-sctp will internally throw an unhandled Error that
  // will terminate the whole Node process (it can not be caught by the app!).
  //
  // In addition, even setting a super high PMTU (i.e. 200000), the number of
  // messages and bytes received by mediasoup won't match the expected values.
  // This happens after sending the 5000 bytes message below. The next messages
  // are not really received by mediasoup so the mediasoup DataProducer's stats
  // still show the same received byte and message number.
  await sendData(sctpStream, dataProducer, 100);
  await sendData(sctpStream, dataProducer, 500);
  await sendData(sctpStream, dataProducer, 1000);
  await sendData(sctpStream, dataProducer, 1200);
  await sendData(sctpStream, dataProducer, 2500);
  await sendData(sctpStream, dataProducer, 5000);
  await sendData(sctpStream, dataProducer, 10000);
  await sendData(sctpStream, dataProducer, 15000);
  await sendData(sctpStream, dataProducer, 20000);
}

async function sendData(sctpStream, dataProducer, size) {
  console.log('[INFO] sending a %s bytes long buffer via SCTP...', size);

  const buffer = Buffer.alloc(size, 'X');

  // Set ppid of type WebRTC DataChannel string.
  buffer.ppid = sctp.PPID.WEBRTC_STRING;

  sctpStream.write(buffer);

  // Wait a bit for the mediasoup DataProducer to receive the data.
  await new Promise((resolve) => setTimeout(resolve, 1000));

  // Show mediasoup received data.
  const stats = await dataProducer.getStats();

  console.log(
    '[INFO] mediasoup DataProducer received a total of %s bytes from the SCTP socket in %s different messages',
    stats[0].bytesReceived, stats[0].messagesReceived);
}
```

**Comment by latysheff** [comment]
Thanks for the snippet. I'll look into it.

**Comment by ibc** [comment]
NOTE: in order to install mediasoup you need this common [requirements](https://mediasoup.org/documentation/v3/mediasoup/installation/#linux-osx-and-any-nix-system) in your host. And then: `npm install mediasoup@3`

**Comment by ibc** [comment]
Note, I've modified the code a bit:

```js
const worker = await mediasoup.createWorker({
    logLevel: 'debug',
    logTags: [ 'sctp' ]
  });
```

this will enable logs of mediasoup related to SCTP. mediasoup also uses the `debug` module so just run the script with `DEBUG="*"` at the beginning.

**Comment by ibc** [comment]
In fact, those are the logs of mediasoup. As you can see, node-sctp does not send any byte when the Buffer size is >= 10000 bytes (even if the given PMTU is 99999);

```
$ DEBUG="*mediasoup:worker*" node node-sctp-issue.js 999999
[INFO] running with PMTU 999999
[INFO] creating a mediasoup Worker, Router and PlainRtpTransport...
  mediasoup:worker[pid:81159] DepUsrSCTP::Start() | usrsctp periodic check started +0ms
[INFO] creating a UDP socket...
[INFO] creating a SCTP socket...
[INFO] waiting for the SCTP assoiation to be open...
  mediasoup:worker[pid:81159] RTC::SctpAssociation::OnUsrSctpReceiveSctpNotification() | SCTP association connected, streams [out:512, in:512] +9ms
[INFO] creating a SCTP stream...
[INFO] creating a mediasoup DataProducer associated to the SCTP stream...


[INFO] sending a 100 bytes long buffer via SCTP...
  mediasoup:worker[pid:81159] RTC::SctpAssociation::onRecvSctpData() | data chunk received [length:100, streamId:1, SSN:0, TSN:2726501331, PPID:51, context:0, flags:8] +4ms
[INFO] mediasoup DataProducer received a total of 100 bytes from the SCTP socket in 1 different messages


[INFO] sending a 500 bytes long buffer via SCTP...
  mediasoup:worker[pid:81159] RTC::SctpAssociation::onRecvSctpData() | data chunk received [length:500, streamId:1, SSN:1, TSN:2726501332, PPID:51, context:0, flags:8] +1s
[INFO] mediasoup DataProducer received a total of 600 bytes from the SCTP socket in 2 different messages


[INFO] sending a 1000 bytes long buffer via SCTP...
  mediasoup:worker[pid:81159] RTC::SctpAssociation::onRecvSctpData() | data chunk received [length:1000, streamId:1, SSN:2, TSN:2726501333, PPID:51, context:0, flags:8] +1s
[INFO] mediasoup DataProducer received a total of 1600 bytes from the SCTP socket in 3 different messages


[INFO] sending a 1200 bytes long buffer via SCTP...
  mediasoup:worker[pid:81159] RTC::SctpAssociation::onRecvSctpData() | data chunk received [length:1200, streamId:1, SSN:3, TSN:2726501334, PPID:51, context:0, flags:8] +1s
[INFO] mediasoup DataProducer received a total of 2800 bytes from the SCTP socket in 4 different messages


[INFO] sending a 2500 bytes long buffer via SCTP...
  mediasoup:worker[pid:81159] RTC::SctpAssociation::onRecvSctpData() | data chunk received [length:2500, streamId:1, SSN:4, TSN:2726501335, PPID:51, context:0, flags:8] +1s
[INFO] mediasoup DataProducer received a total of 5300 bytes from the SCTP socket in 5 different messages


[INFO] sending a 5000 bytes long buffer via SCTP...
  mediasoup:worker[pid:81159] RTC::SctpAssociation::onRecvSctpData() | data chunk received [length:5000, streamId:1, SSN:5, TSN:2726501336, PPID:51, context:0, flags:8] +1s
[INFO] mediasoup DataProducer received a total of 10300 bytes from the SCTP socket in 6 different messages


[INFO] sending a 10000 bytes long buffer via SCTP...
[INFO] mediasoup DataProducer received a total of 10300 bytes from the SCTP socket in 6 different messages

------------ so no new data received now -------------

[INFO] sending a 15000 bytes long buffer via SCTP...
[INFO] mediasoup DataProducer received a total of 10300 bytes from the SCTP socket in 6 different messages

------------ so no new data received now -------------

[INFO] sending a 20000 bytes long buffer via SCTP...
[INFO] mediasoup DataProducer received a total of 10300 bytes from the SCTP socket in 6 different messages

------------ so no new data received now -------------

[INFO] run() succeeds :)
```

**Comment by ibc** [comment]
ok, I've improved the script a bit so now two command line arguments are required and the script will just try to send a single SCTP message:

```
USAGE: node-sctp-issue.js SIZE PMTU

  - SIZE : Size in bytes of the message to send
  - PMTU : PMTU for node-sctp
```

**Comment by ibc** [comment]
And I've updated the script again:

```
USAGE: node-sctp-issue.js SIZE PMTU [COUNT] [TIMEOUT]

  - SIZE    : Size in bytes of the message to send
  - PMTU    : PMTU for node-sctp
  - COUNT   : Number of messages to send all together (default: 1)
  - TIMEOUT : Time in seconds to wait for mediasoup DataProducer to receive all sent bytes (default: 3)
```

Which makes it clear that the problem is not the amount of in-flight SCTP messages in node-sctp, but the size of each message compared to the given `PMTU` (as shown in the previous comment).

BTW, if **many** messages are sent, not all bytes are sent anyway:

```
$ node node-sctp-issue.js 1100 1200 10000 4

[INFO] running with SIZE:1100, PMTU:1200, COUNT:10000, TIMEOUT:4
[INFO] creating a mediasoup Worker, Router and PlainRtpTransport...
[INFO] creating a UDP socket...
[INFO] creating a SCTP socket...
[INFO] waiting for the SCTP assoiation to be open...
[INFO] creating a SCTP stream...
[INFO] creating a mediasoup DataProducer associated to the SCTP stream...

[INFO] sending a 1100 bytes long buffer via SCTP...
[INFO] sending a 1100 bytes long buffer via SCTP...
[INFO] sending a 1100 bytes long buffer via SCTP...
[INFO] sending a 1100 bytes long buffer via SCTP...
[INFO] sending a 1100 bytes long buffer via SCTP...
[INFO] sending a 1100 bytes long buffer via SCTP...
[...] // same log up to 10000 lines as expected

[WARN] total sent bytes (11000000) from SCTP socket do not match mediasoup DataProducer received total bytes (3206500)
[ERROR]: run() failed: Error: not all bytes received
    at run (/private/tmp/node-sctp-issue/node-sctp-issue.js:176:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  [stack]: 'Error: not all bytes received\n' +
    '    at run (/private/tmp/node-sctp-issue/node-sctp-issue.js:176:11)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
  [message]: 'not all bytes received'
}
```

**Comment by ibc** [comment]
It's strange:

* If you set PMTU to 1500 (default value) and send a message of 20000 bytes, it works:

```
$ DEBUG="mediasoup:worker*" node node-sctp-issue.js 20000 1500 1

[INFO] running with SIZE:20000, PMTU:1500, COUNT:1, TIMEOUT:3
  mediasoup:worker[pid:68635] DepUsrSCTP::Start() | usrsctp periodic check started +0ms
[INFO] waiting for the sending SCTP assoiation to be open...
  mediasoup:worker[pid:68635] RTC::SctpAssociation::OnUsrSctpReceiveSctpNotification() | SCTP association connected, streams [out:512, in:512] +10ms
[INFO] creating a sending SCTP stream...
[INFO] creating a mediasoup DataProducer associated to the SCTP stream...
[INFO] waiting for the receiving SCTP assoiation to be open...
  mediasoup:worker[pid:68635] RTC::SctpAssociation::OnUsrSctpReceiveSctpNotification() | SCTP association connected, streams [out:512, in:512] +3ms
[INFO] creating a mediasoup DataConsumer...
[INFO] sending a 20000 bytes long buffer via SCTP...
  mediasoup:worker[pid:68635] RTC::SctpAssociation::onRecvSctpData() | data chunk received [length:20000, streamId:1, SSN:0, TSN:1704073687, PPID:51, context:0, flags:8] +8ms
[INFO] mediasoup DataProducer received a total of 20000 bytes from the SCTP socket in 1 different messages
[INFO] mediasoup DataConsumer sent a total of 20000 bytes originated by the SCTP socket in 1 different messages
[INFO] run() succeeds :)
```

* And if you set PMTU to 1500 and send a message of **150000** bytes, it also works, but somehow, node-sctp sends **2** different SCTP messages instead of just one! (note `SSN:0` and `SSN:1` in the SCTP DATA chunks received by mediasoup):

```
$ DEBUG="mediasoup:worker*" node node-sctp-issue.js 150000 1500 1

[INFO] running with SIZE:150000, PMTU:1500, COUNT:1, TIMEOUT:3
  mediasoup:worker[pid:68646] DepUsrSCTP::Start() | usrsctp periodic check started +0ms
[INFO] waiting for the sending SCTP assoiation to be open...
  mediasoup:worker[pid:68646] RTC::SctpAssociation::OnUsrSctpReceiveSctpNotification() | SCTP association connected, streams [out:512, in:512] +9ms
[INFO] creating a sending SCTP stream...
[INFO] creating a mediasoup DataProducer associated to the SCTP stream...
[INFO] waiting for the receiving SCTP assoiation to be open...
  mediasoup:worker[pid:68646] RTC::SctpAssociation::OnUsrSctpReceiveSctpNotification() | SCTP association connected, streams [out:512, in:512] +3ms
[INFO] creating a mediasoup DataConsumer...
[INFO] sending a 150000 bytes long buffer via SCTP...
  mediasoup:worker[pid:68646] RTC::SctpAssociation::onRecvSctpData() | data chunk received [length:66608, streamId:1, SSN:0, TSN:3084284694, PPID:51, context:0, flags:0] +19ms
  mediasoup:worker[pid:68646] RTC::SctpAssociation::onRecvSctpData() | data chunk received [length:64412, streamId:1, SSN:0, TSN:3084284694, PPID:51, context:0, flags:8] +0ms
  mediasoup:worker[pid:68646] RTC::SctpAssociation::onRecvSctpData() | data chunk received [length:18980, streamId:1, SSN:1, TSN:3084284785, PPID:51, context:0, flags:8] +4ms
[INFO] mediasoup DataProducer received a total of 150000 bytes from the SCTP socket in 2 different messages
[INFO] mediasoup DataConsumer sent a total of 150000 bytes originated by the SCTP socket in 2 different messages
[INFO] run() succeeds :)
``` 

* And if you set PMTU to 1500 and send a message of 1500 bytes, then **BUMP!**:

```
$ DEBUG="mediasoup:worker*" node node-sctp-issue.js 1500 1500 1

[INFO] running with SIZE:1500, PMTU:1500, COUNT:1, TIMEOUT:3
  mediasoup:worker[pid:68657] DepUsrSCTP::Start() | usrsctp periodic check started +0ms
[INFO] waiting for the sending SCTP assoiation to be open...
  mediasoup:worker[pid:68657] RTC::SctpAssociation::OnUsrSctpReceiveSctpNotification() | SCTP association connected, streams [out:512, in:512] +8ms
[INFO] creating a sending SCTP stream...
[INFO] creating a mediasoup DataProducer associated to the SCTP stream...
[INFO] waiting for the receiving SCTP assoiation to be open...
  mediasoup:worker[pid:68657] RTC::SctpAssociation::OnUsrSctpReceiveSctpNotification() | SCTP association connected, streams [out:512, in:512] +3ms
[INFO] creating a mediasoup DataConsumer...
[INFO] sending a 1500 bytes long buffer via SCTP...
_stream_writable.js:465
    throw new ERR_MULTIPLE_CALLBACK();
    ^

Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
    at onwrite (_stream_writable.js:465:11)
    at /Users/ibc/tmp/node-sctp-issue/node_modules/sctp/lib/sockets.js:134:9
    at /Users/ibc/tmp/node-sctp-issue/node_modules/sctp/lib/sockets.js:174:11
    at /Users/ibc/tmp/node-sctp-issue/node_modules/sctp/lib/association.js:1658:11
    at /Users/ibc/tmp/node-sctp-issue/node_modules/sctp/lib/association.js:1335:13
    at Array.forEach (<anonymous>)
    at /Users/ibc/tmp/node-sctp-issue/node_modules/sctp/lib/association.js:1332:19
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_MULTIPLE_CALLBACK'
}
```

**Comment by latysheff** [comment]
If one need to control message boundaries (so that they have same SSN), we again need to hijack Buffer object, though it can be done internally, I hope.
Currently, socket API splits chunks at about RWND size before feeding into SCTP API.
This was done quite ugly, and must be rewritten. 

Proper buffering with highWaterMark should be done in sockets, and SCTP API should allow arbitrary buffer size in SEND()

**Comment by ibc** [comment]
> Currently, socket API splits chunks at about RWND size before feeding into SCTP API.
This was done quite ugly, and must be rewritten.

Yep, a message given to `write()` must not be splitted  into N SCTP messages because the remote application is supposed to receive a single "message" rather than 2 messages (that probably will be invalid).

**Comment by ibc** [comment]
Well, I've written a gist with a more complete test script and failing examples:

https://gist.github.com/ibc/17ed95cd2f08b84222c8820b034cd391

**Comment by latysheff** [comment]
Made comment on gist. Please use new highWaterMark (bytes) value in sctp.connect() for larger buffers.
Also pushed version 0.19 of sctp package, addressing multiple callbacks.

Let me know your thoughts.
